[tool.poetry]
name = "ner-model"
version = "1.0.0"
authors = []
description = ""
readme = ""

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
transformers = "==4.41.1"
torch = "==2.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
